CREATE USER ds WITH PASSWORD 'ds';
GRANT ALL PRIVILEGES ON DATABASE easyrecovery TO ds;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ds;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ds;